// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiYAMCil-TRcJNS1wBwVKuefxQ7g6cY3c',
    appId: '1:714185754787:web:ba614476a072784ce1d716',
    messagingSenderId: '714185754787',
    projectId: 'plug-in-team',
    authDomain: 'plug-in-team.firebaseapp.com',
    storageBucket: 'plug-in-team.firebasestorage.app',
    measurementId: 'G-E62M6HPJHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-rUhdMQjic8Efqfc-16Je5kIzUzXkAbM',
    appId: '1:714185754787:android:fa8167ae2ec05768e1d716',
    messagingSenderId: '714185754787',
    projectId: 'plug-in-team',
    storageBucket: 'plug-in-team.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBubrekbyDcRE1pdxKK65W-Su44s7AaYmc',
    appId: '1:714185754787:ios:b2375a9daf448355e1d716',
    messagingSenderId: '714185754787',
    projectId: 'plug-in-team',
    storageBucket: 'plug-in-team.firebasestorage.app',
    iosClientId: '714185754787-tf626d5oanmrmn6dac60mi6ieme9nfis.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectPlugin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBubrekbyDcRE1pdxKK65W-Su44s7AaYmc',
    appId: '1:714185754787:ios:b2375a9daf448355e1d716',
    messagingSenderId: '714185754787',
    projectId: 'plug-in-team',
    storageBucket: 'plug-in-team.firebasestorage.app',
    iosClientId: '714185754787-tf626d5oanmrmn6dac60mi6ieme9nfis.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectPlugin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiYAMCil-TRcJNS1wBwVKuefxQ7g6cY3c',
    appId: '1:714185754787:web:b4c059fadfcfcd76e1d716',
    messagingSenderId: '714185754787',
    projectId: 'plug-in-team',
    authDomain: 'plug-in-team.firebaseapp.com',
    storageBucket: 'plug-in-team.firebasestorage.app',
    measurementId: 'G-443CJP53N2',
  );

}